server:
    port: 80
dubbo:
    protocol:
       port: -1
    application:
       name: dubbo-consumer
    scan:
       basePackages: org.consumer.dubbo.controller
    registry:
       address: zookeeper://127.0.0.1:2181

       
      